### ISSUE TITLE
Twilio Alert Trigger

### ISSUE THREAD

**Issue by mehadesai** [ajency/ProjectJ#228]
Is there some exception that is happening in our code that we are not catching, that probably triggers an error on Twilio? The account has been blocked once before when this happened and I fear it will be blocked again

**Comment by verlekar-viraj** [comment]
I checked logs for sendSMS function which i had written, all calls were successful with no exception or errors. If it is used somewhere else too then it needs to be checked.
We can check twilio debugger as suggested by above image, to find out more.
I guess as the last line says "Delete this Alert Trigger" will solve the case but not the correct way to fix it i feel. Will require RCA to be done.

**Comment by verlekar-viraj** [comment]
Twilio error log : "The destination number you are trying to reach is blocked from receiving this message (ex. due to blacklisting).

Number : +919561967851

Twilio messages are listed as promotional. If end user has blocked promotional messages then he/she wont receive any messages from twilio. If not this & the number is not blacklisted, should get in touch with Twilio support with the number that is causing this error and they will look into it.

"Delete this Alert Trigger" will only stop mails being sent when error is encountered, it will not stop blocking the numbers.

Also twilio has limitations for Indian numbers
https://support.twilio.com/hc/en-us/articles/223134167-Limitations-sending-SMS-messages-to-Indian-mobile-devices

**Comment by mehadesai** [comment]
Awesome! This helps. 

@SavantMaithili does not need to unblock/deregister herself. It's okay. :)

At least we can say with some sense of surety that this won't happen for actual Hong Kong numbers.

Closing this issue.
